/**
 * src/playbooks/runner.ts
 *
 * Playbook executor (Track E5).
 *
 * Handles:
 *  - Pre-flight guard checks (kill switch, quota ledger stub)
 *  - Dry-run estimation
 *  - Subagent brief materialisation (writes markdown brief to .data/playbooks/briefs/)
 *  - Composed playbook step sequencing with halt-on-failure + resumability
 *
 * The actual job-runner / run-dispatcher wiring is done externally;
 * this module manages lifecycle and emits PlaybookRun records.
 */

import fs from 'fs';
import path from 'path';
import { randomUUID } from 'crypto';
import { fileURLToPath } from 'url';
import {
  type Playbook,
  type PlaybookRun,
  type PlaybookRunStep,
  PlaybookGuardTripped,
  ComposedPlaybookStepFailed,
  SubagentBriefIncompleteError,
} from './types.js';
import { getPlaybook, isKillSwitchTripped, validateParams } from './registry.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const BRIEFS_DIR = path.join(ROOT, '.data/playbooks/briefs');
const RUNS_DIR = path.join(ROOT, '.data/playbooks/runs');

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

// ---------------------------------------------------------------------------
// Run persistence (file-backed, simple)
// ---------------------------------------------------------------------------

function runPath(runId: string): string {
  return path.join(RUNS_DIR, `${runId}.json`);
}

function persistRun(run: PlaybookRun): void {
  ensureDir(RUNS_DIR);
  fs.writeFileSync(runPath(run.run_id), JSON.stringify(run, null, 2), 'utf-8');
}

export function loadRun(runId: string): PlaybookRun | null {
  const p = runPath(runId);
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf-8')) as PlaybookRun;
  } catch {
    return null;
  }
}

export function listRuns(playbookId?: string): PlaybookRun[] {
  ensureDir(RUNS_DIR);
  const files = fs.readdirSync(RUNS_DIR).filter((f) => f.endsWith('.json'));
  const runs = files
    .map((f) => {
      try {
        return JSON.parse(fs.readFileSync(path.join(RUNS_DIR, f), 'utf-8')) as PlaybookRun;
      } catch {
        return null;
      }
    })
    .filter((r): r is PlaybookRun => r !== null);

  if (playbookId) return runs.filter((r) => r.playbook_id === playbookId);
  return runs.sort((a, b) => b.started_at.localeCompare(a.started_at));
}

// ---------------------------------------------------------------------------
// Guard checks
// ---------------------------------------------------------------------------

function checkGuards(playbook: Playbook): void {
  if (playbook.guards.kill_switch && isKillSwitchTripped()) {
    throw new PlaybookGuardTripped(playbook.id, 'kill_switch');
  }
  // quota_ledger: stub — always passes for now; real impl reads quota table
}

// ---------------------------------------------------------------------------
// Subagent brief materialiser
// ---------------------------------------------------------------------------

function materialiseBrief(playbook: Playbook, params: Record<string, unknown>): string {
  ensureDir(BRIEFS_DIR);

  const paramsSection = Object.entries(params)
    .map(([k, v]) => `- **${k}**: ${JSON.stringify(v)}`)
    .join('\n');

  const guardSection = [
    playbook.guards.kill_switch ? '✓ Kill switch checked' : '',
    playbook.guards.quota_ledger ? '✓ Quota ledger checked' : '',
    playbook.guards.requires_tier ? `✓ Requires tier: ${playbook.guards.requires_tier}` : '',
  ]
    .filter(Boolean)
    .join('\n');

  const md = `# Playbook Brief: ${playbook.title}

**Playbook ID:** \`${playbook.id}\`
**Generated:** ${new Date().toISOString()}
**Executor:** ${playbook.executor}

## Description

${playbook.description}

## Parameters

${paramsSection || '_(none specified)_'}

## Guards

${guardSection}

## Instructions for Operator

This brief was auto-generated by the Playbook Layer (Track E5).
Review the parameters above, then launch the actual ${playbook.executor} run.

> **Judgment required** — this playbook requires human review before execution.
> Giri should inspect the parameters and approve before firing the agent.
`;

  const filename = `${playbook.id}-${Date.now()}.md`;
  const briefPath = path.join(BRIEFS_DIR, filename);
  fs.writeFileSync(briefPath, md, 'utf-8');
  return briefPath;
}

// ---------------------------------------------------------------------------
// Composed step runner
// ---------------------------------------------------------------------------

async function runComposedSteps(
  run: PlaybookRun,
  playbook: Playbook,
): Promise<void> {
  const steps = playbook.steps ?? [];
  const stepStates: PlaybookRunStep[] = steps.map((id) => ({
    playbook_id: id,
    status: 'pending',
  }));
  run.steps = stepStates;
  persistRun(run);

  for (const step of stepStates) {
    step.status = 'running';
    step.started_at = new Date().toISOString();
    persistRun(run);

    try {
      // Real execution delegates to the job-runner / run-dispatcher;
      // here we validate that the step playbook id resolves.
      const childPlaybook = getPlaybook(step.playbook_id);
      if (!childPlaybook) {
        throw new Error(`Step playbook '${step.playbook_id}' not found in registry`);
      }
      // Stub: mark step complete. Real impls wire into job-runner here.
      step.status = 'completed';
      step.completed_at = new Date().toISOString();
    } catch (err) {
      step.status = 'failed';
      step.completed_at = new Date().toISOString();
      step.error = String(err);
      run.status = 'failed';
      run.completed_at = new Date().toISOString();
      run.error = `Step '${step.playbook_id}' failed`;
      persistRun(run);
      throw new ComposedPlaybookStepFailed(
        playbook.id,
        step.playbook_id,
        String(err),
      );
    }

    persistRun(run);
  }
}

// ---------------------------------------------------------------------------
// Public: estimate (dry run)
// ---------------------------------------------------------------------------

export interface RunEstimateResult {
  playbook_id: string;
  params: Record<string, unknown>;
  estimate: ReturnType<Playbook['estimator']>;
  validation_errors: string[];
}

export function estimateRun(
  playbookId: string,
  params: Record<string, unknown>,
): RunEstimateResult {
  const playbook = getPlaybook(playbookId);
  if (!playbook) throw new Error(`Playbook '${playbookId}' not found`);

  const validation_errors = validateParams(playbook, params);
  const estimate = playbook.estimator(params);

  return { playbook_id: playbookId, params, estimate, validation_errors };
}

// ---------------------------------------------------------------------------
// Public: launch
// ---------------------------------------------------------------------------

export interface LaunchResult {
  run: PlaybookRun;
  brief_path?: string;
}

export async function launchPlaybook(
  playbookId: string,
  params: Record<string, unknown>,
  options: { dry_run?: boolean } = {},
): Promise<LaunchResult> {
  const playbook = getPlaybook(playbookId);
  if (!playbook) throw new Error(`Playbook '${playbookId}' not found`);

  // Validate params
  const errors = validateParams(playbook, params);
  if (errors.length) {
    throw new SubagentBriefIncompleteError(playbookId, errors);
  }

  // Guard check
  checkGuards(playbook);

  const run: PlaybookRun = {
    run_id: randomUUID(),
    playbook_id: playbookId,
    params,
    status: 'running',
    started_at: new Date().toISOString(),
  };

  // Dry-run path
  if (params.dry_run || options.dry_run) {
    run.status = 'completed';
    run.completed_at = new Date().toISOString();
    persistRun(run);
    return { run };
  }

  // Subagent: materialise brief + mark pending (human must fire)
  if (playbook.executor === 'subagent') {
    const briefPath = materialiseBrief(playbook, params);
    run.brief_path = briefPath;
    run.status = 'pending';
    persistRun(run);
    return { run, brief_path: briefPath };
  }

  persistRun(run);

  // Composed: run steps sequentially
  if (playbook.steps?.length) {
    try {
      await runComposedSteps(run, playbook);
    } catch {
      // run already marked failed inside runComposedSteps
      return { run };
    }
  }

  run.status = 'completed';
  run.completed_at = new Date().toISOString();
  persistRun(run);

  return { run };
}

// ---------------------------------------------------------------------------
// Public: abort
// ---------------------------------------------------------------------------

export function abortRun(runId: string): PlaybookRun {
  const run = loadRun(runId);
  if (!run) throw new Error(`Run '${runId}' not found`);
  if (run.status === 'completed' || run.status === 'aborted') {
    throw new Error(`Run '${runId}' is already in terminal state '${run.status}'`);
  }
  run.status = 'aborted';
  run.completed_at = new Date().toISOString();
  persistRun(run);
  return run;
}
