/**
 * src/generation/practice-item-factory/cost.ts
 *
 * Single source of truth for "what does one practice item roughly cost" —
 * reused by both src/generation/dry-run.ts's estimateRunCost() (the
 * pre-launch operator-facing estimate) and src/generation/batch/poller.ts's
 * OrchestratorOpts.estimatePerJobUsd (the orchestrator's own budget check
 * inside prepare(), see CLAUDE.md's v4.25.0 note on model-id "parallel
 * truths" — one number, not two that can drift apart).
 *
 * Rough by design, same bar as cost-meter.ts's header comment: within 30%
 * is good enough to catch an order-of-magnitude blunder, not a replacement
 * for real invoicing. mcq/msq price in a dual-model-consensus second leg
 * (answer-check.ts); nat prices in one Wolfram call instead.
 */

import { priceForCall } from '../cost-meter';
import type { PracticeItemFormat } from './types';

const GENERATION_TOKENS = { input: 700, output: 1400 }; // question + distractors + solution steps
const SECOND_LEG_TOKENS = { input: 500, output: 150 }; // mcq/msq consensus solve — short, answer-only

const DEFAULT_MODEL_ID = 'gemini-2.5-flash';

export interface PracticeItemCostBreakdown {
  generation_usd: number;
  verification_usd: number;
  total_usd: number;
}

/**
 * Estimated USD for one practice item of the given format, generated by
 * `modelId` (defaults to the batch pipeline's fixed primary,
 * gemini-adapter.ts's DEFAULT_MODEL). nat items add one Wolfram call; mcq
 * and msq add one second-leg generation call on top of the primary
 * generation (the actual secondary provider isn't known ahead of launch —
 * approximated using the primary's price, same "rough" bar as the rest of
 * this estimator).
 */
export function estimatePracticeItemCostBreakdownUsd(
  format: PracticeItemFormat,
  modelId = DEFAULT_MODEL_ID,
): PracticeItemCostBreakdown {
  const generation_usd = priceForCall({
    model: modelId,
    input_tokens: GENERATION_TOKENS.input,
    output_tokens: GENERATION_TOKENS.output,
  });
  const verification_usd =
    format === 'nat'
      ? priceForCall({ model: 'wolfram' })
      : priceForCall({
          model: modelId,
          input_tokens: SECOND_LEG_TOKENS.input,
          output_tokens: SECOND_LEG_TOKENS.output,
        });
  return { generation_usd, verification_usd, total_usd: generation_usd + verification_usd };
}

/** Just the total — the common case (per-job budget checks, simple sums). */
export function estimatePracticeItemCostUsd(format: PracticeItemFormat, modelId = DEFAULT_MODEL_ID): number {
  return estimatePracticeItemCostBreakdownUsd(format, modelId).total_usd;
}

/** Sum of estimatePracticeItemCostUsd() over a list of specs. */
export function estimatePracticeItemBatchCostUsd(
  specs: ReadonlyArray<{ format: PracticeItemFormat }>,
  modelId = DEFAULT_MODEL_ID,
): number {
  return specs.reduce((sum, s) => sum + estimatePracticeItemCostUsd(s.format, modelId), 0);
}

/** Summed generation/verification breakdown over a list of specs. */
export function estimatePracticeItemBatchBreakdownUsd(
  specs: ReadonlyArray<{ format: PracticeItemFormat }>,
  modelId = DEFAULT_MODEL_ID,
): PracticeItemCostBreakdown {
  return specs.reduce<PracticeItemCostBreakdown>(
    (acc, s) => {
      const b = estimatePracticeItemCostBreakdownUsd(s.format, modelId);
      return {
        generation_usd: acc.generation_usd + b.generation_usd,
        verification_usd: acc.verification_usd + b.verification_usd,
        total_usd: acc.total_usd + b.total_usd,
      };
    },
    { generation_usd: 0, verification_usd: 0, total_usd: 0 },
  );
}
