// @ts-nocheck
/**
 * src/content/kag-store.ts
 *
 * Append-only store for KAG (Knowledge-Augmented Generation) corpus entries.
 *
 * Entries are generated by kag-concept-generator.ts at runtime or by the
 * kag-corpus-builder CLI. Embeddings are stored as float[] (in-memory) —
 * upgrade trigger is 2000+ entries, at which point pgvector is warranted.
 *
 * Priority: this store is checked at tier 0 in the content router —
 * before user subscriptions — because KAG entries are pre-verified with
 * Wolfram grounding and are the highest-confidence content available.
 */

import { createAppendLog } from '../lib/append-log';

export interface KagEntry {
  concept_id: string;
  content: string;
  wolfram_grounding: string | null;
  embedding: number[];
  generated_at: string;
  source_model: string;
}

const KAG_PATH = '.data/kag-corpus.jsonl';

const kag_log = createAppendLog<KagEntry>({
  path: KAG_PATH,
  isValid: (p: any) =>
    p && typeof p === 'object'
      && typeof p.concept_id === 'string'
      && typeof p.content === 'string'
      && Array.isArray(p.embedding),
});

let _index: Map<string, KagEntry> | null = null;

function getIndex(): Map<string, KagEntry> {
  if (_index) return _index;
  const idx = new Map<string, KagEntry>();
  for (const e of kag_log.readAll()) {
    idx.set(e.concept_id, e);
  }
  _index = idx;
  return idx;
}

export function getKagEntry(concept_id: string): KagEntry | null {
  return getIndex().get(concept_id) ?? null;
}

export function addKagEntry(entry: KagEntry): void {
  kag_log.append(entry);
  getIndex().set(entry.concept_id, entry);
}

export function getKagStats(): { total: number } {
  return { total: getIndex().size };
}

/** Find by embedding similarity — in-memory cosine search. */
export function findKagBySimilarity(
  query_embedding: number[],
  top_k: number = 3,
  threshold: number = 0.82,
): Array<{ entry: KagEntry; score: number }> {
  const results: Array<{ entry: KagEntry; score: number }> = [];
  for (const entry of getIndex().values()) {
    if (entry.embedding.length !== query_embedding.length) continue;
    const score = cosineSimilarity(query_embedding, entry.embedding);
    if (!Number.isFinite(score)) continue;   // guard: blank/zero vector → skip
    if (score >= threshold) results.push({ entry, score });
  }
  return results.sort((a, b) => b.score - a.score).slice(0, top_k);
}

export function _resetKagForTests(): void {
  _index = null;
  kag_log.truncate();
}

function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0, na = 0, nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na  += a[i] * a[i];
    nb  += b[i] * b[i];
  }
  const denom = Math.sqrt(na) * Math.sqrt(nb);
  if (denom === 0) return 0;
  const sim = dot / denom;
  return Number.isFinite(sim) ? sim : 0;
}
