#!/usr/bin/env tsx
/**
 * provision-tenant.ts
 *
 * Bootstraps a fresh Vidhya tenant against any PostgreSQL database.
 * Intended for platform teams running one deployment per tenant / school.
 *
 * Usage:
 *   npx tsx scripts/provision-tenant.ts \
 *     --db-url  postgres://user:pass@host:5432/dbname \
 *     --tenant-id  acme-prep \
 *     --admin-email  admin@acme.com \
 *     [--admin-role  admin]        # default: admin
 *     [--dry-run]                  # print env stub only, no DB writes
 *
 * What it does:
 *   1. Runs all pending migrations from supabase/migrations/ (idempotent).
 *   2. Creates an admin user_profiles row so the first human can log in.
 *   3. Prints a ready-to-use .env stub for this tenant's deployment.
 *
 * The script is safe to re-run — migrations track their own applied state
 * and the admin upsert is ON CONFLICT DO NOTHING.
 */

import pg from 'pg';
import { randomUUID } from 'crypto';
import { autoMigrate } from '../src/db/auto-migrate.js';

const { Pool } = pg;

// ---------------------------------------------------------------------------
// Arg parsing
// ---------------------------------------------------------------------------

function parseArgs(): {
  dbUrl: string;
  tenantId: string;
  adminEmail: string;
  adminRole: string;
  dryRun: boolean;
} {
  const args = process.argv.slice(2);
  const get = (flag: string): string | undefined => {
    const i = args.indexOf(flag);
    return i !== -1 ? args[i + 1] : undefined;
  };

  const dbUrl = get('--db-url');
  const tenantId = get('--tenant-id');
  const adminEmail = get('--admin-email');

  if (!dbUrl || !tenantId || !adminEmail) {
    console.error(`
Usage: npx tsx scripts/provision-tenant.ts \\
  --db-url      postgres://user:pass@host:5432/dbname \\
  --tenant-id   acme-prep \\
  --admin-email admin@acme.com \\
  [--admin-role admin] \\
  [--dry-run]
`);
    process.exit(1);
  }

  return {
    dbUrl,
    tenantId,
    adminEmail,
    adminRole: get('--admin-role') || 'admin',
    dryRun: args.includes('--dry-run'),
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const { dbUrl, tenantId, adminEmail, adminRole, dryRun } = parseArgs();

  console.log(`\n[provision] Tenant: ${tenantId}`);
  console.log(`[provision] Admin:  ${adminEmail} (role: ${adminRole})`);
  if (dryRun) console.log('[provision] DRY RUN — no DB writes\n');

  if (!dryRun) {
    // Step 1: Migrations
    const pool = new Pool({ connectionString: dbUrl, max: 3 });
    try {
      console.log('\n[provision] Step 1/2 — applying migrations...');
      const applied = await autoMigrate(pool);
      console.log(`[provision] Migrations done (${applied} newly applied)`);

      // Step 2: Seed admin user
      console.log('\n[provision] Step 2/2 — seeding admin user...');
      const adminId = randomUUID();

      // user_profiles references auth.users via FK. On a plain Postgres deploy,
      // migration 000_local_auth_stub.sql provides the auth.users stub table.
      // We insert into auth.users first so the FK resolves.
      await pool.query(`
        INSERT INTO auth.users (id, email, created_at, updated_at)
        VALUES ($1, $2, NOW(), NOW())
        ON CONFLICT (id) DO NOTHING
      `, [adminId, adminEmail]);

      await pool.query(`
        INSERT INTO user_profiles (id, email, role, created_at, updated_at)
        VALUES ($1, $2, $3, NOW(), NOW())
        ON CONFLICT (id) DO NOTHING
      `, [adminId, adminEmail, adminRole]);

      console.log(`[provision] Admin user created (id: ${adminId})`);
      console.log(`[provision] Role: ${adminRole}`);
    } finally {
      await pool.end();
    }
  }

  // Step 3: Print .env stub
  const envStub = generateEnvStub({ tenantId, adminEmail, dbUrl, dryRun });
  console.log('\n' + '='.repeat(72));
  console.log('[provision] .env stub for this tenant deployment:');
  console.log('='.repeat(72));
  console.log(envStub);
  console.log('='.repeat(72));

  if (!dryRun) {
    console.log(`\n[provision] Done. Save the .env stub above to deploy tenant "${tenantId}".`);
    console.log('[provision] Start the server: DATABASE_URL=... npx tsx src/server.ts');
  }
}

function generateEnvStub(opts: {
  tenantId: string;
  adminEmail: string;
  dbUrl: string;
  dryRun: boolean;
}): string {
  const { tenantId, adminEmail, dbUrl } = opts;

  return `# ============================================================
# Vidhya tenant: ${tenantId}
# Admin: ${adminEmail}
# Generated by scripts/provision-tenant.ts
# ============================================================

# --- Required ---
DATABASE_URL=${dbUrl}

# Minimum 32 chars. Generate with: openssl rand -hex 32
JWT_SECRET=REPLACE_ME_$(Math.random().toString(36).slice(2, 12).toUpperCase())

# --- LLM provider (set ONE of the following blocks) ---

# Option A: OpenRouter (single key, routes to any model)
OPENROUTER_API_KEY=

# Option B: Anthropic
ANTHROPIC_API_KEY=

# Option C: OpenAI / Azure OpenAI
OPENAI_API_KEY=
# VIDHYA_LLM_PROVIDER=openai
# VIDHYA_LLM_BASE_URL=https://company.openai.azure.com/openai/deployments/gpt-4o
# VIDHYA_LLM_MODEL=gpt-4o

# Option D: Google Gemini
GEMINI_API_KEY=

# Option E: Your own IdP auth (Auth0, Cognito, Clerk)
# VIDHYA_AUTH_MODE=external-jwks
# VIDHYA_JWKS_URI=https://company.auth0.com/.well-known/jwks.json
# VIDHYA_ROLE_CLAIM_PATH=role
# VIDHYA_SKIP_DB_ROLE_LOOKUP=true

# --- Optional ---
PORT=8080
# WOLFRAM_APP_ID=           # enables Tier 3 verification
# VIDHYA_LEDGER_PR=off      # disable weekly digest PRs
`.replace(
    'REPLACE_ME_$(Math.random().toString(36).slice(2, 12).toUpperCase())',
    randomUUID().replace(/-/g, '').slice(0, 32).toUpperCase(),
  );
}

main().catch((err) => {
  console.error('[provision] Fatal error:', err.message);
  process.exit(1);
});
